# Step 7: the results on one page, and the record of the software used.
#
# Writes  Output/wave1_results_summary.md       key numbers from the tables of steps 1 to 6, with the
#                                               reading rules of ANALYSIS-PLAN.md next to them
#         Output/wave1_r_session_info.txt       R version, package versions, seed, pre-analysis commit

source("00_functions.R")

read_out <- function(name) read.csv(file.path(OUTPUT, paste0(PREFIX, name)), check.names = FALSE, encoding = "UTF-8")
desc <- read_out("descriptives_numeric.csv")
redundant <- read_out("correlation_pairs_redundant.csv")
cors <- read_out("correlations_with_price.csv")
fit <- read_out("regressions_fit.csv")
imp <- read_out("regressions_importance.csv")
diag <- read_out("regressions_diagnostics.csv")
cv <- read_out("cv_summary.csv")
sel <- read_out("cv_selection_frequency.csv")
rfi <- read_out("cv_rf_importance.csv")
tab <- read_out("analysis_table.csv")

f2 <- function(x) sprintf("%.2f", x)
f3 <- function(x) sprintf("%.3f", x)
md_table <- function(df, digits = 3) {
  fmt <- function(col) {
    if (!is.numeric(col)) return(as.character(col))
    if (all(col == round(col), na.rm = TRUE)) return(ifelse(is.na(col), "NA", formatC(col, format = "d", big.mark = ",")))
    formatC(col, digits = digits, format = "f")
  }
  cells <- as.data.frame(lapply(df, fmt), stringsAsFactors = FALSE)
  c(paste0("| ", paste(names(df), collapse = " | "), " |"), paste0("|", paste(rep("---", ncol(df)), collapse = "|"), "|"),
    apply(cells, 1, function(r) paste0("| ", paste(r, collapse = " | "), " |")))
}

primary <- "log 30-day average price"
fit_primary <- fit[fit$outcome == primary & fit$model %in% c("spec1_august_state", "spec2_september_no_price_link", "spec3_plus_two_way_and_mechanical", "spec2plus_category8"), ]
fit_spot <- fit[fit$outcome == "log spot price" & fit$model %in% c("spec1_august_state", "spec2_september_no_price_link", "spec3_plus_two_way_and_mechanical"), ]
rehearsal <- fit[grepl("specR", fit$model), ]
coefs <- read_out("regressions_coefficients.csv")
rehearsal_terms <- coefs[grepl("specR", coefs$model) & coefs$term != "(Intercept)", ]
rehearsal_terms <- rehearsal_terms[order(-rehearsal_terms$delta_r2_drop_one), ][1:3, ]
top_imp <- function(model, k = 6) {
  x <- imp[imp$model == model & imp$outcome == primary, ][1:k, ]
  sprintf("%s (standardised %s, delta R2 %s, p %s)", x$term, f2(x$beta_standardised), f3(x$delta_r2_drop_one), f3(x$p_hc3))
}
cv_primary <- cv[cv$outcome == "log_price_avg30" & cv$model != "null", ]
cv_wide <- reshape(cv_primary[, c("feature_set", "model", "r2_oos_mean", "r2_oos_sd")], idvar = "model", timevar = "feature_set", direction = "wide")
names(cv_wide) <- sub("r2_oos_mean\\.", "R2 ", sub("r2_oos_sd\\.", "SD ", names(cv_wide)))
best_f2 <- cv_primary[cv_primary$feature_set == "F2" & cv_primary$model != "ols_composites_leave_one_team_out", ]
best_f2 <- best_f2[which.max(best_f2$r2_oos_mean), ]
loto <- cv[cv$model == "ols_composites_leave_one_team_out", ]
top_cor <- cors[cors$outcome == "log_price_avg30", ][1:10, ]

lines <- c(
  "# Wave 1 results summary",
  "",
  sprintf("Generated by `Code/analysis/07_summary.R` on %s from the tables in `Output/`. The plan these results follow is `Code/analysis/ANALYSIS-PLAN.md`, frozen in commit `%s` before any correlation with the price was computed.",
          format(Sys.Date(), "%d %b %Y"), PRE_ANALYSIS_COMMIT),
  "",
  "## What the numbers can and cannot say",
  "",
  "One cross-section of 128 subnets at the end of September 2026. Features measured at the same time as the price move with it by construction; the only clean time order inside wave 1 is August features against the September price, and the forward test is the wave 2 return (plan, section 9). With 124 regression rows, a standardised coefficient below about 0.2 cannot be told from zero; the cross-validation spread over repeats understates the uncertainty of each R2 (Bates, Hastie and Tibshirani 2023).",
  "",
  "## Step 1: descriptives",
  "",
  sprintf("%d numeric or binary variables and 5 categorical ones (`wave1_descriptives_numeric.csv`, `wave1_descriptives_categorical.csv`). %d variables have missing values, almost all because the thing measured does not exist for that subnet (no repository: 24 subnets, no X account: 36, no white paper: 96 to 105, no miner paid: 23). Skewness above 2 in %d variables; counts and amounts are therefore log-transformed in every later step.",
          nrow(desc), sum(desc$n_missing > 0), sum(desc$skewness > 2, na.rm = TRUE)),
  "",
  "## Step 2: correlations",
  "",
  sprintf("Among the 141 features, %d pairs correlate at |Spearman| >= 0.8 and %d at >= 0.95 (`wave1_correlation_pairs_redundant.csv`): the file holds far fewer distinct quantities than columns, which is why composites are used. The complete matrix including the outcomes is `wave1_correlations_all_spearman.csv`.",
          nrow(redundant), sum(abs(redundant$spearman) >= 0.95)),
  "",
  "Strongest Spearman correlations with the log 30-day average price (`wave1_correlations_with_price.csv`; among 141 null features the largest |r| would be about 0.24):",
  "",
  md_table(data.frame(variable = top_cor$variable, kind = top_cor$kind, n = top_cor$n, rho = top_cor$spearman_rho, p_BH = top_cor$p_bh), 3),
  "",
  "## Steps 3 and 4: composites and regressions",
  "",
  "Missing values: one availability indicator per block, feature set to 0 where it does not apply (plan, section 4). Composites: unit-weighted means of signed z-scores per block (plan, section 5; `wave1_analysis_table.csv`). Regressions on the 124 subnets observed for the whole window (`wave1_regressions_fit.csv`, `wave1_regressions_coefficients.csv`):",
  "",
  md_table(data.frame(model = fit_primary$model, outcome = "log 30-day average price", slopes = fit_primary$slopes, R2 = fit_primary$r2, adj_R2 = fit_primary$adj_r2, note = fit_primary$note), 3),
  "",
  md_table(data.frame(model = fit_spot$model, outcome = "log spot price", slopes = fit_spot$slopes, R2 = fit_spot$r2, adj_R2 = fit_spot$adj_r2), 3),
  "",
  "Largest contributions by drop-one delta R2 (`wave1_regressions_importance.csv`), log 30-day average price:",
  "",
  "- Specification 1 (August state): ", paste0("  - ", top_imp("spec1_august_state")),
  "- Specification 2 (September, no known price link): ", paste0("  - ", top_imp("spec2_september_no_price_link")),
  "- Specification 3 (plus two-way and mechanical): ", paste0("  - ", top_imp("spec3_plus_two_way_and_mechanical")),
  "",
  sprintf("Rehearsal of the wave 2 test (`%s`): R2 %s, adjusted %s, n %d. Reading: the September return regressed on the August state plus the lagged log price. Largest contributions: %s. The plan expected a result near zero; what the rehearsal picks up is which kinds of subnets fell most in a month in which the median subnet lost 13%%, not a forecast.",
          rehearsal$model[1], f2(rehearsal$r2[1]), f2(rehearsal$adj_r2[1]), rehearsal$n[1],
          paste(sprintf("%s (standardised %s, delta R2 %s, p %s)", rehearsal_terms$term, f2(rehearsal_terms$beta_standardised),
                        f3(rehearsal_terms$delta_r2_drop_one), f3(rehearsal_terms$p_hc3)), collapse = ", ")),
  "",
  "Diagnostics (`wave1_regressions_diagnostics.csv`): largest VIF, Breusch-Pagan p, the five most influential subnets and the R2 without them:",
  "",
  md_table(diag[diag$outcome == primary & grepl("^spec[123]_", diag$model) & !grepl("pc1|without", diag$model),
                c("model", "max_vif", "p_breusch_pagan", "five_most_influential_netuids", "r2", "r2_without_five")], 3),
  "",
  "## Step 5: out-of-sample accuracy",
  "",
  "Repeated 10-fold cross-validation, 20 repeats, teams kept together, every estimated quantity fitted on the training fold (plan, section 8). Out-of-sample R2 = 1 - MSE(model) / MSE(training-fold mean), mean over repeats, with the SD over repeats (`wave1_cv_summary.csv`, `wave1_cv_results_by_repeat.csv`, `wave1_cv_plot.png`). Log 30-day average price:",
  "",
  md_table(cv_wide, 3),
  "",
  sprintf("Best model on F2 (the set without known price links): %s, R2 %s (SD %s), above zero in %s of the repeats. Leave-one-team-out OLS on specification 2: R2 %s. Lasso on F2 kept most often: %s (`wave1_cv_selection_frequency.csv`). Random-forest permutation importance on F2, top five: %s (`wave1_cv_rf_importance.csv`).",
          best_f2$model, f2(best_f2$r2_oos_mean), f2(best_f2$r2_oos_sd), sprintf("%.0f%%", 100 * best_f2$share_repeats_above_zero), f2(loto$r2_oos_mean[1]),
          paste(sprintf("%s (%.0f%%)", sel$variable[1:5], 100 * sel$share_of_training_folds_kept[1:5]), collapse = ", "),
          paste(rfi$variable[1:5], collapse = ", ")),
  "",
  "## Deviations from the plan",
  "",
  "- Amendment 1 (5 Oct 2026, `ANALYSIS-PLAN.md` section 11): a subnet without a GitHub repository or an X account gets the weakest observed value on every repository or X variable instead of the average of the subnets that have one. The OLS results are unchanged by construction (the indicators `has_repo` and `has_x` absorb any constant fill); the penalised models and the random forest were rerun.",
  "- `miner_paid` and `started` (and `has_holders` in specification 3) are exactly collinear with the flags `flag_full_burn_30d` and `startup_mode` in the 124-row sample and were dropped by the fitting routine; the fit tables note it per model.",
  "- `flag_placeholder_identity` and `startup_mode` were moved from prediction set F2 to F1 after the pre-analysis commit, so that F1 carries the controls of specification 1 as the plan states.",
  "- `startup_mode` was taken out of specification 1 (and of the rehearsal model): `started_lag` nests it, and the one subnet that started emissions in September but not in August (netuid 36) would otherwise be the only observation identifying it, with leverage 1 and undefined HC3 standard errors.",
  "- Specification 1 includes the lagged attention composite (August commentator posts and podcasts), which specification 2 does not include at all (attention is a two-way feature and enters in specification 3). The two R2 values are therefore not a like-for-like comparison of August and September state.",
  "",
  "## Files",
  "",
  "Every table and figure in `Output/` starts with `wave1_`; `Code/analysis/README.md` says how to reproduce them.")
save_text(lines, "results_summary.md")

info <- c(capture.output(sessionInfo()), "", sprintf("seed: %d", SEED), sprintf("pre-analysis commit: %s", PRE_ANALYSIS_COMMIT),
          sprintf("glmnet %s, randomForest %s", as.character(packageVersion("glmnet")), as.character(packageVersion("randomForest"))),
          sprintf("dataset sha256 (Input/subnets_wave1_2026-09-30.csv): %s", unname(tools::sha256sum(DATASET))))
save_text(info, "r_session_info.txt")
cat("summary written: Output/wave1_results_summary.md\n")
